/**
 * Created by GennadySX on @2020
 */


export const language = {
    en: {
        spanish: "Española",
        english: "English",
        login: "Login",
        register: "Register",
        password: "Password",
        confirm: "Confirm",
        sign_up: "Sign up",
        sign_in: "Sign in",
        your: "your",
        fullName: "Full name",
        enterYourName: "Enter your name",
        enterLogin: "Enter login",
        enterYourPassword: "Enter your password",
        enterYourPhoneNumber: "Enter your phone number",
        enterYourAddress: "Enter your address",
        yourPassword: "Your password",
        confirmPassword: "Confirm password",
        additionsToPizza: "Additions to pizza",
        addCart: "Add to cart as ",
        cash: "$",
        small: "Small",
        middle: "Middle",
        large: "Large",
        choose: "Choose",
        cart: "Cart",
        totalSum: "Total sum",
        confirmOrder: "Confirm order",
        phone: "Phone",
        phoneNumber: "phone number",
        address: "Address",
        order: "Order",
        loading: "Loading",
    },
    sp: {
        spanish: "Española",
        english: "English",
        login: "Iniciar sesión",
        register: "Registrarse",
        password: "Contraseña",
        confirm: "Confirmar",
        sign_up: "Regístrate",
        sign_in: "Registrarse",
        your: "tu",
        fullName: "Nombre completo",
        enterYourName: "Introduzca su nombre",
        enterLogin: "Ingrese inicio de sesión",
        enterYourPassword: "Ingresa tu contraseña",
        enterYourPhoneNumber: "Ingrese su número telefónico",
        enterYourAddress: "Ingrese su direccion",
        yourPassword: "Tu contraseña",
        confirmPassword: "Confirmar contraseña",
        additionsToPizza: "Adiciones a la pizza",
        addCart: "Añadir al carrito como ",
        cash: "€",
        small: "Pequeña",
        middle: "Medio",
        large: "Grande",
        choose: "Escoger",
        cart: "Carro",
        totalSum: "Suma total",
        confirmOrder: "Confirmar pedido",
        phone: "Teléfono",
        phoneNumber: "número de teléfono",
        address: "Habla a",
        order: "Orden",
        loading: "Cargando",
    }
}